#!/usr/bin/env python3
"""
SKATE — regenerate_index.py

Rebuild INDEX.md from the actual conversation entries on disk. Idempotent:
run it any time. Replaces the existing INDEX.md. Entries are grouped by
session, then sorted by date descending.

Usage:
    python tools/regenerate_index.py
    python tools/regenerate_index.py --dry-run   # print, don't write

No external dependencies. Pure stdlib.
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

SKATE_ROOT = Path(__file__).resolve().parent.parent
CONVERSATIONS = SKATE_ROOT / "conversations"
INDEX_FILE = SKATE_ROOT / "INDEX.md"

UNASSIGNED_SESSION = "unassigned"


def parse_frontmatter(text: str) -> dict:
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    data: dict = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key, value = key.strip(), value.strip()
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            if not inner:
                data[key] = []
            else:
                items = [s.strip().strip('"').strip("'") for s in inner.split(",")]
                data[key] = [s for s in items if s]
        elif value.startswith('"') and value.endswith('"'):
            data[key] = value[1:-1]
        else:
            data[key] = value
    return data


def collect_entries() -> list[dict]:
    if not CONVERSATIONS.exists():
        print(f"ERROR: {CONVERSATIONS} not found", file=sys.stderr)
        sys.exit(1)
    entries: list[dict] = []
    for md in sorted(CONVERSATIONS.rglob("*.md")):
        text = md.read_text(encoding="utf-8", errors="ignore")
        fm = parse_frontmatter(text)
        session = str(fm.get("session", "") or "").strip()
        entries.append({
            "path": md.relative_to(SKATE_ROOT).as_posix(),
            "date": fm.get("date", "?"),
            "title": fm.get("title", md.stem),
            "type": str(fm.get("type", fm.get("entry_type", "note")) or "note").strip().lower(),
            "session": session or UNASSIGNED_SESSION,
            "session_label": str(fm.get("session_label", "") or "").strip(),
            "themes": fm.get("themes", []) or [],
            "tags": fm.get("tags", []) or [],
        })
    return entries


def session_display(key: str, entries: list[dict]) -> str:
    if key == UNASSIGNED_SESSION:
        return "Unassigned"
    for e in entries:
        if e["session"] == key and e["session_label"]:
            return e["session_label"]
    return key.replace("-", " ").title()


def build_index(entries: list[dict]) -> str:
    entries_sorted = sorted(entries, key=lambda e: (e["date"], e["title"]), reverse=True)
    today = datetime.date.today().isoformat()

    out: list[str] = []
    out.append("# SKATE — Master Index\n")
    out.append(f"**Last updated:** {today}  ")
    out.append(f"**Auto-generated by:** `tools/regenerate_index.py`\n")
    out.append("This index is rebuilt from the conversation entries on disk, grouped by session and sorted by date "
               "descending (newest first). To rebuild after adding entries, run `python tools/regenerate_index.py`.\n")
    out.append("---\n")

    # All entries table
    out.append("## All entries\n")
    out.append("| Date | Type | Title | Session | Themes | File |")
    out.append("|---|---|---|---|---|---|")
    for e in entries_sorted:
        themes = ", ".join(e["themes"]) if e["themes"] else "—"
        session = e["session"] if e["session"] != UNASSIGNED_SESSION else "—"
        out.append(
            f"| {e['date']} | {e['type']} | {e['title']} | "
            f"{session} | {themes} | [link]({e['path']}) |"
        )
    out.append("")
    out.append("---\n")

    # By session, then date descending
    out.append("## By session\n")
    by_session: dict[str, list[dict]] = defaultdict(list)
    for e in entries_sorted:
        by_session[e["session"]].append(e)
    session_keys = sorted(
        by_session.keys(),
        key=lambda key: (key == UNASSIGNED_SESSION, key.lower()),
    )
    for key in session_keys:
        items = by_session[key]
        out.append(f"### {session_display(key, items)} ({len(items)})")
        for e in items:
            out.append(f"- {e['date']} — {e['type']} — {e['title']}")
        out.append("")
    out.append("---\n")

    # Stats
    out.append("## Statistics\n")
    type_counts = Counter(e["type"] for e in entries_sorted)
    theme_counts = Counter(theme for e in entries_sorted for theme in e["themes"])
    dates = sorted(e["date"] for e in entries_sorted if e["date"] not in ("", "?"))
    out.append(f"- **Total entries:** {len(entries_sorted)}")
    out.append(f"- **Sessions:** {len(by_session)}")
    out.append(f"- **Object types used:** {len(type_counts)}")
    if type_counts:
        most_common = type_counts.most_common(1)[0]
        out.append(f"- **Most common type:** {most_common[0]} ({most_common[1]} entries)")
    if dates:
        out.append(f"- **Date range:** {dates[0]} to {dates[-1]}")
    out.append("")

    if theme_counts:
        out.append("**Top themes:**")
        for theme, n in theme_counts.most_common(10):
            if n >= 2:
                out.append(f"- `{theme}` — {n} entries")
        out.append("")

    out.append("---\n")
    out.append("*Run `python tools/regenerate_index.py` after adding entries.*")
    out.append("")

    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description="Regenerate INDEX.md from conversation entries.")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing INDEX.md")
    args = parser.parse_args()

    entries = collect_entries()
    if not entries:
        print("No entries found — nothing to index.", file=sys.stderr)
        sys.exit(1)

    content = build_index(entries)

    if args.dry_run:
        print(content)
    else:
        INDEX_FILE.write_text(content, encoding="utf-8")
        print(f"Wrote {INDEX_FILE.relative_to(SKATE_ROOT)} — {len(entries)} entries indexed.")


if __name__ == "__main__":
    main()
